# you'll also need to pip install ./batch until batch is in pip somewhere
name: hail-ci
dependencies:
- python>=3.7
- requests
- flask
- pytest
- pip
- pip:
    - google-cloud-storage
    - flask-cors
